In [0]:
from google.colab import files
uploaded=files.upload()

Saving sample_submission.csv to sample_submission (1).csv
Saving Test.csv to Test (1).csv
Saving Train.csv to Train (1).csv


In [0]:

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)


In [0]:
df=pd.read_csv("Train.csv")

In [0]:
df.drop(['numis_holiday'],axis=1,inplace=True)

In [0]:
df

date_time is_holiday  ...      weather_description  traffic_volume
0       10/2/2012 9:00       None  ...         scattered clouds            5545
1      10/2/2012 10:00       None  ...            broken clouds            4516
2      10/2/2012 11:00       None  ...          overcast clouds            4767
3      10/2/2012 12:00       None  ...          overcast clouds            5026
4      10/2/2012 13:00       None  ...            broken clouds            4918
5      10/2/2012 14:00       None  ...             sky is clear            5181
6      10/2/2012 15:00       None  ...             sky is clear            5584
7      10/2/2012 16:00       None  ...             sky is clear            6015
8      10/2/2012 17:00       None  ...               few clouds            5791
9      10/2/2012 18:00       None  ...               few clouds            4770
10     10/2/2012 19:00       None  ...               few clouds            3539
11     10/2/2012 20:00       None  ...             sky is clear            2784
12     10/2/2012 21:00       None  ...             sky is clear            2361
13     10/2/2012 22:00       None  ...             sky is clear            1529
14     10/2/2012 23:00       None  ...             sky is clear             963
15      10/3/2012 0:00       None  ...             sky is clear             506
16      10/3/2012 1:00       None  ...             sky is clear             321
17      10/3/2012 2:00       None  ...             sky is clear             273
18      10/3/2012 3:00       None  ...             sky is clear             367
19      10/3/2012 4:00       None  ...             sky is clear             814
20      10/3/2012 5:00       None  ...             sky is clear            2718
21      10/3/2012 6:00       None  ...             sky is clear            5673
22      10/3/2012 8:00       None  ...             sky is clear            6511
23      10/3/2012 9:00       None  ...             sky is clear            5471
24     10/3/2012 12:00       None  ...             sky is clear            5097
25     10/3/2012 13:00       None  ...             sky is clear            4887
26     10/3/2012 14:00       None  ...             sky is clear            5337
27     10/3/2012 15:00       None  ...             sky is clear            5692
28     10/3/2012 16:00       None  ...             sky is clear            6137
29     10/3/2012 18:00       None  ...               few clouds            4623
...                ...        ...  ...                      ...             ...
33720  5/17/2017 10:00       None  ...                     mist            4517
33721  5/17/2017 10:00       None  ...  light intensity drizzle            4517
33722  5/17/2017 11:00       None  ...            moderate rain            4666
33723  5/17/2017 12:00       None  ...    proximity shower rain            4990
33724  5/17/2017 12:00       None  ...                     mist            4990
33725  5/17/2017 13:00       None  ...    proximity shower rain            4789
33726  5/17/2017 13:00       None  ...  light intensity drizzle            4789
33727  5/17/2017 14:00       None  ...    proximity shower rain            5185
33728  5/17/2017 15:00       None  ...    proximity shower rain            5590
33729  5/17/2017 16:00       None  ...            moderate rain            6426
33730  5/17/2017 16:00       None  ...                     mist            6426
33731  5/17/2017 17:00       None  ...            moderate rain            5763
33732  5/17/2017 17:00       None  ...                     mist            5763
33733  5/17/2017 18:00       None  ...            moderate rain            4864
33734  5/17/2017 18:00       None  ...                     mist            4864
33735  5/17/2017 18:00       None  ...  light intensity drizzle            4864
33736  5/17/2017 18:00       None  ...   proximity thunderstorm            4864
33737  5/17/2017 19:00       None  ...  light intensity drizzle            3136
33738  5/17/2

In [0]:
# Part 1 - Data Preprocessing

# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Importing the training set
training_set = df.iloc[:, -1].values

# Feature Scaling
from sklearn.preprocessing import MinMaxScaler
sc = MinMaxScaler(feature_range = (0, 1))
training_set_scaled = sc.fit_transform(training_set.reshape(-1,1))

In [0]:
np.shape(training_set_scaled)

(33750, 1)

In [0]:
# Creating a data structure with 60 timesteps and 1 output
X_train = []
y_train = []
for i in range(60, 33750):
    X_train.append(training_set_scaled[i-60:i, 0])
    y_train.append(training_set_scaled[i, 0])
X_train, y_train = np.array(X_train), np.array(y_train)

# Reshaping
X_train = np.reshape(X_train, (X_train.shape[0], X_train.shape[1], 1))



# Part 2 - Building the RNN

# Importing the Keras libraries and packages
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM
from keras.layers import Dropout

# Initialising the RNN
regressor = Sequential()

# Adding the first LSTM layer and some Dropout regularisation
regressor.add(LSTM(units = 50, return_sequences = True, input_shape = (X_train.shape[1], 1)))
regressor.add(Dropout(0.2))

# Adding a second LSTM layer and some Dropout regularisation
regressor.add(LSTM(units = 50, return_sequences = True))
regressor.add(Dropout(0.2))
# Adding a third LSTM layer and some Dropout regularisation
regressor.add(LSTM(units = 50, return_sequences = True))
regressor.add(Dropout(0.2))

# Adding a sixth LSTM layer and some Dropout regularisation
regressor.add(LSTM(units = 50))
regressor.add(Dropout(0.2))

# Adding the output layer
regressor.add(Dense(units = 1))

# Compiling the RNN
regressor.compile(optimizer = 'adam', loss = 'mean_squared_error')

# Fitting the RNN to the Training set
regressor.fit(X_train, y_train, epochs = 1, batch_size = 16)

Epoch 1/1
33690/33690 [==============================] - 575s 17ms/step - loss: 0.0252


In [0]:
df.head()

date_time is_holiday  ...  weather_description  traffic_volume
0   10/2/2012 9:00       None  ...     scattered clouds            5545
1  10/2/2012 10:00       None  ...        broken clouds            4516
2  10/2/2012 11:00       None  ...      overcast clouds            4767
3  10/2/2012 12:00       None  ...      overcast clouds            5026
4  10/2/2012 13:00       None  ...        broken clouds            4918

[5 rows x 15 columns]

In [2]:
X=df.iloc[:,-1].values
X=X[33750-60:]
len(X)

NameError: ignored

In [1]:
from sklearn.preprocessing import MinMaxScaler
sc = MinMaxScaler(feature_range = (0, 1))
X=sc.fit_transform(X.reshape(-1,1))
X

NameError: ignored

In [0]:
temp=regressor.predict(np.reshape(X,(-1,60,1)))
np.shape(X)

(60, 1)

In [0]:
result=[]
for i in range(14454):
  temp=regressor.predict(np.reshape(X,(-1,60,1)))
  result.append(sc.inverse_transform(temp))
  X=np.concatenate((X[1:],temp))

  

KeyboardInterrupt: ignored

In [0]:
result

[array([[0.09059]], dtype=float32),
 array([[0.02589086]], dtype=float32),
 array([[-0.04130737]], dtype=float32),
 array([[-0.09841788]], dtype=float32),
 array([[-0.12648672]], dtype=float32),
 array([[-0.09372282]], dtype=float32),
 array([[0.05460326]], dtype=float32),
 array([[0.39069986]], dtype=float32),
 array([[0.78071916]], dtype=float32),
 array([[0.87723804]], dtype=float32),
 array([[0.7857633]], dtype=float32),
 array([[0.724373]], dtype=float32),
 array([[0.72353274]], dtype=float32),
 array([[0.7505604]], dtype=float32),
 array([[0.7837945]], dtype=float32),
 array([[0.8070329]], dtype=float32),
 array([[0.81078005]], dtype=float32),
 array([[0.7964297]], dtype=float32),
 array([[0.77124584]], dtype=float32),
 array([[0.74167347]], dtype=float32),
 array([[0.71080685]], dtype=float32),
 array([[0.67937684]], dtype=float32),
 array([[0.64695466]], dtype=float32),
 array([[0.612718]], dtype=float32),
 array([[0.5758128]], dtype=float32),
 array([[0.5354036]], dtype=float3